### ISSUE TITLE
Fix: No Latest tag for uniclogs-yamcs on DockerHub

### ISSUE THREAD

**Issue by jiangha4** [oresat/uniclogs-yamcs#51] opened 2023-04-15 19:24 UTC
**Describe the bug**
Docker image doesn't exist on docker hub. 
`Error response from daemon: manifest for oresat/uniclogs-yamcs:latest not found: manifest unknown: manifest unknown`

**To Reproduce**
Run `docker pull oresat/uniclogs-yamcs:latest`

**Expected behavior**
The image to pull

**Comment by dmitri-mcguckin** [comment] 2023-04-15 22:50
This will require follow up discussion on this.

Our Dockerhub Organization has been impacted by Docker Hub's recent [policy change](https://devclass.com/2023/03/15/docker-to-users-of-free-team-orgs-one-month-to-pay-up-or-we-freeze-account-and-images-go/) on free teams.


A side on general-adminitration for GH issues:

This is not a bug, this classifies as discussion. Please do not use the bug tag for this class of issue, please use one or more of the either the discussion, documentation, or awaiting dependency tags.

**Comment by dmitri-mcguckin** [comment] 2023-04-15 23:05
Just to add some clarification:

Our free Dockerhub-team has been discontinued since they now cost money, so we will need to find a new place to host our Docker images. Once we find or make a new host we can re-direct our images there.

This was discussed in a SW meeting sometime a month ago, but we didn't make a final decision on it. We can add it to the agenda of next meeting.

**Comment by jiangha4** [comment] 2023-04-15 23:52
This is on the main README page to do. If this is suppose to be a discussion, then the README should be updated to reflect these changes. 

As it stands, this is a bug with the readme and onboarding process. 

There is not a clear process on how to onboard to this project.

**Comment by dmitri-mcguckin** [comment] 2023-04-16 00:42
This is not a bug as it does not pertain to a bug directly related to the software, it is a dev-ops issue. I can appreciate that not all of the guidelines are in place, we had not-too-long ago transferred this repo from the OreSat org to the UniClOGS org, so not all documents, tags, and project boards have been transferred over.

I would appreciate if you respect that, since this is, as you say, something you are still on boarding to, and this is not your repository to maintain.

That said, I would be happy to talk about this at the next SW meeting.

**Closed as completed** 2023-05-02 03:01 UTC
Labels: dev-ops
